### USER
POST http://localhost:9499/api/users/
Content-Type: application/json

{

}

### 
GET http://localhost:9499/api/users/
Content-Type: application/json
Authorization: bearer Imtoken12345withnumberandletters156

{

}


### CATEGORY
GET http://localhost:9499/api/categories/items
Content-Type: application/json
Authorization: bearer Imtoken12345withnumberandletters156

{
   
}

### ITEM
POST http://localhost:9499/api/items/
Content-Type: application/json
Authorization: bearer Imtoken12345withnumberandletters156

{
   "item":{
       "id": null,
       "name": "Brocolis",
       "note": "", 
       "image": "",
       "category": {
           "id": 2,
           "name": "Vegetable", 
           "userId": 1
       }
   }
}

### LIST
PATCH http://localhost:9499/api/lists/
Content-Type: application/json
Authorization: bearer Imtoken12345withnumberandletters156

{
   "list":{
       "id": 4,
       "name": "list name ed",
       "state": "EDITTING",
       "items": []
   }
}

### 

PATCH  http://localhost:9499/api/lists/
Content-Type: application/json
Authorization: bearer Imtoken12345withnumberandletters156

{
   "list":{
       "id": 9,
       "name": "list name with items",
       "state": "EDITTING",
       "items": [
           {
            "id": 70,
            "name": "Brocolis",
            "quantity": 5,
            "isChecked": true,
            "note": "", 
            "image": "",
            "category": {
                "id": 2,
                "name": "Vegetable", 
                "userId": 1
            }
   }
   ]
   }
}